#!/usr/bin/env python3
##
## EPITECH PROJECT, 2018
## 104_intersection
## File description:
## math
##

import sys
import math

def check_for_err():
    halp = open("help", "r")

    if len(sys.argv) > 1 and sys.argv[1] == "-h":
        print(halp.read())
        sys.exit(0)
    elif len(sys.argv) < 9:
        print("Too few arguments. Try -h for more informations.")
        sys.exit(84)
    elif len(sys.argv) > 9:
        print("Too much arguments. Try -h for more informations.")
        sys.exit(84)

    i = 1
    while i < 9:
        try:
            flag = int(sys.argv[i])
        except ValueError:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
        i += 1

    flag = int(sys.argv[2])
    if flag != 1 or flag != 2 or flag != 3:
        print("Flag error. Try -h for more informations.")
        sys.exit(84)

check_for_err()
print('fin')
